services:
  - type: web
    name: medical-assistant-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SESSION_DIR
        value: /tmp/flask_session
      - key: OPENAI_API_KEY
        sync: false  # You'll need to set this manually in Render dashboard
    healthCheckPath: /
    autoDeploy: false 